### ISSUE TITLE
a better look for snippets

### ISSUE THREAD

**Issue by singzing** [WPManageNinja/easy-code-manager#31]
this plugin is great but can be improved the appearance a little bit. The font size is too small, and delete key is too small and not noticeable, so I have a css a little bit it, and hope you guys will imporve the UI next version.

```css
.fsnip_secondary_menu {
    font-size: 1.2em;
}

.group_file_name {
    font-size: 1.2em !important;
}

.fsn_label {
    font-size: .7em !important;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 3px 5px !important;
    line-height: 1 !important;
}

.snippet_actions {
    font-size: 1em !important;
    display: flex;
    align-items: center;
    justify-content: center;
}

span:has(.el-icon) {
    display: flex;
    align-items: center;
    justify-content: center;

    .el-icon {
        margin-right: 3px;
    }
}

.fsnip_delete {
    color: red !important;   
}
``` 

and last but not least, could you add an option that can Import and Export the snippet codes, in case to backup or so on...
